# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20161210_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
