# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20161113_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('byLikes', django.db.models.manager.Manager()),
            ],
        ),
    ]
