# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20161113_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
