# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20161218_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.Profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
    ]
