# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20161218_0114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together=set([('profile', 'question')]),
        ),
    ]
