# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 02:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20161218_0149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('top', django.db.models.manager.Manager()),
            ],
        ),
    ]
